from ._ClientAlbums import SpotifyClientFunctionality_Albums
from ._ClientArtists import SpotifyClientFunctionality_Artists
from ._ClientGenres import SpotifyClientFunctionality_Genres
from ._ClientMarkets import SpotifyClientFunctionality_Markets
from ._ClientSearch import SpotifyClientFunctionality_Search
from ._ClientTracks import SpotifyClientFunctionality_Tracks
from ._ClientUsers import SpotifyClientFunctionality_Users
